// GENERATED by tools/gen.py from sheets/*.json. Do not edit; change the sheet.
namespace UKAudio
{
    internal static class Sheets
    {
        internal sealed class AudioRow
        {
            public string id;
            public string kind;
            public string bundles;
            public string[] match;
            public double volume;
            public bool verified;
            public string note;
        }
        internal static readonly AudioRow[] Audio = new[]
        {
            new AudioRow { id = "sfx_rank_up", kind = "sfx", bundles = "*.bundle", match = new[] { "(?i)style.*(up|gain)", "(?i)rank.*up", "(?i)^ding", "(?i)coin" }, volume = 0.8, verified = false, note = "ULTRAKILL has no built-in per-rank sound (mods add one); pick a real UI/reward clip from clip-index.txt" },
            new AudioRow { id = "sfx_rank_up_high", kind = "sfx", bundles = "*.bundle", match = new[] { "(?i)final.?rank", "(?i)rank.*(s|reveal)", "(?i)parry" }, volume = 0.9, verified = false, note = "a punchier real clip for S and above; the end-of-level rank sound is the first choice" },
            new AudioRow { id = "sfx_rank_ultrakill", kind = "sfx", bundles = "*.bundle", match = new[] { "(?i)p.?rank", "(?i)final.?rank", "(?i)parry" }, volume = 1.0, verified = false, note = "the P-rank reveal if present" },
            new AudioRow { id = "sfx_rank_down", kind = "sfx", bundles = "*.bundle", match = new[] { "(?i)(hurt|damage).*(v1|player)", "(?i)whiplash.*(break|miss)", "(?i)error" }, volume = 0.6, verified = false, note = "a real 'lost it' clip" },
            new AudioRow { id = "sfx_mode_switch", kind = "sfx", bundles = "*.bundle", match = new[] { "(?i)weapon.?switch", "(?i)(revolver|pistol).*(spin|switch)", "(?i)click" }, volume = 0.7, verified = false, note = "weapon-variation switch click" },
            new AudioRow { id = "music_clean", kind = "music", bundles = "music_assets*.bundle", match = new[] { "(?i)clean" }, volume = 0.9, verified = false, note = "ULTRAKILL levels ship a calm 'clean' and an intense 'battle' version of each track; the helper pairs them by shared name" },
            new AudioRow { id = "music_battle", kind = "music", bundles = "music_assets*.bundle", match = new[] { "(?i)battle" }, volume = 1.0, verified = false, note = "battle half of the same pair" },
        };
        internal sealed class MusicTiersRow
        {
            public string id;
            public int order;
            public string clean_layer;
            public string battle_layer;
            public double clean_gain;
            public double battle_gain;
            public double crossfade_s;
        }
        internal static readonly MusicTiersRow[] MusicTiers = new[]
        {
            new MusicTiersRow { id = "calm", order = 0, clean_layer = "music_clean", battle_layer = "music_battle", clean_gain = 0.35, battle_gain = 0.0, crossfade_s = 3.0 },
            new MusicTiersRow { id = "drive", order = 1, clean_layer = "music_clean", battle_layer = "music_battle", clean_gain = 0.75, battle_gain = 0.0, crossfade_s = 2.0 },
            new MusicTiersRow { id = "combat", order = 2, clean_layer = "music_clean", battle_layer = "music_battle", clean_gain = 0.0, battle_gain = 0.8, crossfade_s = 1.0 },
            new MusicTiersRow { id = "ultra", order = 3, clean_layer = "music_clean", battle_layer = "music_battle", clean_gain = 0.0, battle_gain = 1.0, crossfade_s = 0.5 },
        };
        internal sealed class RanksRow
        {
            public string id;
            public int order;
            public string letter;
            public string name;
            public int threshold;
            public double decay_per_s;
            public string color;
            public string up_sound;
            public string music_tier;
            public double power_move_mult;
            public double power_anim_mult;
            public bool power_absorb_hit;
        }
        internal static readonly RanksRow[] Ranks = new[]
        {
            new RanksRow { id = "d", order = 0, letter = "D", name = "DESTRUCTIVE", threshold = 0, decay_per_s = 6.0, color = "#4A90E2", up_sound = "sfx_rank_up", music_tier = "calm", power_move_mult = 1.0, power_anim_mult = 1.0, power_absorb_hit = false },
            new RanksRow { id = "c", order = 1, letter = "C", name = "CHAOTIC", threshold = 100, decay_per_s = 10.0, color = "#4CD964", up_sound = "sfx_rank_up", music_tier = "calm", power_move_mult = 1.03, power_anim_mult = 1.03, power_absorb_hit = false },
            new RanksRow { id = "b", order = 2, letter = "B", name = "BRUTAL", threshold = 250, decay_per_s = 15.0, color = "#FFCC00", up_sound = "sfx_rank_up", music_tier = "drive", power_move_mult = 1.06, power_anim_mult = 1.06, power_absorb_hit = false },
            new RanksRow { id = "a", order = 3, letter = "A", name = "ANARCHIC", threshold = 450, decay_per_s = 20.0, color = "#FF9500", up_sound = "sfx_rank_up", music_tier = "drive", power_move_mult = 1.1, power_anim_mult = 1.1, power_absorb_hit = false },
            new RanksRow { id = "s", order = 4, letter = "S", name = "SUPREME", threshold = 700, decay_per_s = 27.0, color = "#FF3B30", up_sound = "sfx_rank_up_high", music_tier = "combat", power_move_mult = 1.14, power_anim_mult = 1.15, power_absorb_hit = false },
            new RanksRow { id = "ss", order = 5, letter = "SS", name = "SSADISTIC", threshold = 1000, decay_per_s = 36.0, color = "#FF2D55", up_sound = "sfx_rank_up_high", music_tier = "combat", power_move_mult = 1.18, power_anim_mult = 1.2, power_absorb_hit = false },
            new RanksRow { id = "sss", order = 6, letter = "SSS", name = "SSSHITSTORM", threshold = 1400, decay_per_s = 50.0, color = "#D40000", up_sound = "sfx_rank_up_high", music_tier = "ultra", power_move_mult = 1.22, power_anim_mult = 1.25, power_absorb_hit = false },
            new RanksRow { id = "ultrakill", order = 7, letter = "ULTRAKILL", name = "ULTRAKILL", threshold = 1900, decay_per_s = 70.0, color = "#FFD700", up_sound = "sfx_rank_ultrakill", music_tier = "ultra", power_move_mult = 1.28, power_anim_mult = 1.3, power_absorb_hit = true },
        };
        internal sealed class ModesRow
        {
            public string id;
            public int order;
            public string label;
            public string summary;
            public bool suppress_ron_penalties;
            public string end_score;
            public bool power_buffs;
            public string switch_sound;
        }
        internal static readonly ModesRow[] Modes = new[]
        {
            new ModesRow { id = "clean", order = 0, label = "CLEAN", summary = "Arrests, takedowns and fast clears. Unauthorized force drops you to D.", suppress_ron_penalties = false, end_score = "ron", power_buffs = false, switch_sound = "sfx_mode_switch" },
            new ModesRow { id = "ultrakill", order = 1, label = "ULTRAKILL RULES", summary = "Kills, headshots and multi-kills feed the meter. Best rank is your score.", suppress_ron_penalties = true, end_score = "best_rank", power_buffs = false, switch_sound = "sfx_mode_switch" },
            new ModesRow { id = "power", order = 2, label = "POWER", summary = "Everything earns style. Rank makes you faster. ULTRAKILL rank shrugs off a hit.", suppress_ron_penalties = false, end_score = "best_rank", power_buffs = true, switch_sound = "sfx_mode_switch" },
        };
        internal sealed class SettingsRow
        {
            public string id;
            public string value;
            public string desc;
        }
        internal static readonly SettingsRow[] Settings = new[]
        {
            new SettingsRow { id = "hotkey_mode", value = "F7", desc = "Cycle Clean → ULTRAKILL Rules → Power" },
            new SettingsRow { id = "hotkey_hud", value = "F8", desc = "Show or hide the meter" },
            new SettingsRow { id = "hotkey_recon", value = "F10", desc = "Write classes, hook results and penalty functions to UE4SS.log" },
            new SettingsRow { id = "poll_ms", value = "100", desc = "How often the mod reads the game" },
            new SettingsRow { id = "fire_window_s", value = "0.8", desc = "A death this soon after the player fired counts as theirs" },
            new SettingsRow { id = "aim_cone_deg", value = "10", desc = "Victim must be this close to the crosshair to be the player's kill" },
            new SettingsRow { id = "headshot_cone_deg", value = "2.5", desc = "Head this close to the crosshair = headshot" },
            new SettingsRow { id = "player_reach_cm", value = "350", desc = "Arrests/takedowns closer than this are the player's" },
            new SettingsRow { id = "multikill_window_s", value = "1.5", desc = "Kills this close together are a multikill" },
            new SettingsRow { id = "chain_window_s", value = "4.0", desc = "Neutralizations this close together are a fast clear" },
            new SettingsRow { id = "style_cap", value = "2400", desc = "Meter maximum" },
            new SettingsRow { id = "feed_lines", value = "5", desc = "Lines kept in the HUD feed" },
            new SettingsRow { id = "data_dir", value = "{localappdata}/RoNUltrakill", desc = "Folder for settings.cfg, events.log, clip-index.txt, logs" },
            new SettingsRow { id = "settings_file", value = "{localappdata}/RoNUltrakill/settings.cfg", desc = "Melty writes ULTRAKILL_DIR here before every Play" },
            new SettingsRow { id = "events_file", value = "{localappdata}/RoNUltrakill/events.log", desc = "Lua appends, helper tails" },
            new SettingsRow { id = "heartbeat_file", value = "{localappdata}/RoNUltrakill/helper.alive", desc = "Helper touches it every second" },
            new SettingsRow { id = "game_process", value = "ReadyOrNotSteam-Win64-Shipping|ReadyOrNot-Win64-Shipping", desc = "Helper exits when none of these processes ('|'-separated) is running; the Steam build's exe is ReadyOrNotSteam-Win64-Shipping.exe" },
        };
    }
}
