-- GENERATED by tools/gen.py from sheets/*.json. Do not edit; change the sheet.
local S = {}
S.audio = {
  { id = "sfx_rank_up", kind = "sfx", bundles = "*.bundle", match = {"(?i)^coinflash$", "(?i)^coinflip$"}, volume = 0.8, verified = true, note = "ULTRAKILL has no built-in per-rank sound (mods add one); the coin-ricochet flash, from a real clip-index.txt (sounds.bundle)" },
  { id = "sfx_rank_up_high", kind = "sfx", bundles = "*.bundle", match = {"(?i)^CleanSuccess$", "(?i)^CheckpointActivate$"}, volume = 0.9, verified = true, note = "a punchier real clip for S and above (sounds.bundle)" },
  { id = "sfx_rank_ultrakill", kind = "sfx", bundles = "*.bundle", match = {"(?i)^CleanSuccessBig$", "(?i)^CleanSuccess$"}, volume = 1.0, verified = true, note = "the big success sting (sounds.bundle); the P-rank reveal is not a separate clip" },
  { id = "sfx_rank_down", kind = "sfx", bundles = "*.bundle", match = {"(?i)^FinalDoorFail$", "(?i)^BellDull$"}, volume = 0.6, verified = true, note = "a real 'lost it' clip (sounds.bundle)" },
  { id = "sfx_mode_switch", kind = "sfx", bundles = "*.bundle", match = {"(?i)^switch-1$", "(?i)^ImpactClick$"}, volume = 0.7, verified = true, note = "switch click (sounds.bundle)" },
  { id = "music_clean", kind = "music", bundles = "music_assets*.bundle", match = {"(?i)\\bclean$"}, volume = 0.9, verified = true, note = "ULTRAKILL names the calm version '<level> Clean' (e.g. '0-2 Clean'); pairs are keyed with settings.music_pair_strip" },
  { id = "music_battle", kind = "music", bundles = "music_assets*.bundle", match = {"(?i)^(?!.*\\bclean\\b)[0-9p]-[0-9e]\\b"}, volume = 1.0, verified = true, note = "the intense version is the bare level name ('0-2') or '<name> Battle' ('1-2 Dark Battle')" },
}
S.audio_by_id = {}
for _, r in ipairs(S.audio) do S.audio_by_id[r.id] = r end
S.hooks = {
  { id = "characters", kind = "engine", method = "find_all", target = "world", candidates = {"Character"}, used_by = "every character-state event", implemented = true, verified = true, source = "UE4SS FindAllOf on the engine base class ACharacter; verified RoN UE4SS.log 2026-10-08 (Station hub): FindAllOf Character answered" },
  { id = "class_suspect", kind = "game", method = "recon", target = "Character class name", candidates = {"Suspect", "Cybernetic", "Enemy", "Hostile"}, used_by = "kill / arrest / level_clear classification", implemented = true, verified = false, source = "guess; the mod logs every Character class it meets so the list can be corrected" },
  { id = "class_civilian", kind = "game", method = "recon", target = "Character class name", candidates = {"Civilian", "Hostage", "Innocent"}, used_by = "unauthorized_kill", implemented = true, verified = true, source = "guess; corrected from the class log; verified RoN UE4SS.log 2026-10-08 (Station hub): civilians are Cybernetics_Civilian_V2_C" },
  { id = "class_swat", kind = "game", method = "recon", target = "Character class name", candidates = {"SWAT", "Swat", "Officer", "PlayerCharacter"}, used_by = "ignore squad mates", implemented = true, verified = false, source = "guess; corrected from the class log" },
  { id = "state_dead", kind = "game", method = "call_or_property", target = "Character", candidates = {"IsDeadNotUnconscious", "IsDead", "bIsDead", "bDead"}, used_by = "kill, multikill, unauthorized_kill", implemented = true, verified = true, source = "guess; fallback is health_props <= 0; verified RoN UE4SS.log 2026-10-08 (Station hub): IsDeadNotUnconscious() on Cybernetics_Civilian_V2_C" },
  { id = "state_arrested", kind = "game", method = "call_or_property", target = "Character", candidates = {"IsArrested", "bIsArrested", "bArrested"}, used_by = "arrest, squad_arrest, fast_clear", implemented = true, verified = true, source = "guess; verified RoN UE4SS.log 2026-10-08 (Station hub): IsArrested() on Cybernetics_Civilian_V2_C" },
  { id = "state_surrendered", kind = "game", method = "call_or_property", target = "Character", candidates = {"IsSurrendered", "bIsSurrendered", "bSurrendered"}, used_by = "compliance, unauthorized_kill", implemented = true, verified = true, source = "guess; verified RoN UE4SS.log 2026-10-08 (Station hub): IsSurrendered() on Cybernetics_Civilian_V2_C" },
  { id = "state_incapacitated", kind = "game", method = "call_or_property", target = "Character", candidates = {"IsIncapacitated", "bIsIncapacitated", "bIncapacitated"}, used_by = "takedown", implemented = true, verified = true, source = "guess; verified RoN UE4SS.log 2026-10-08 (Station hub): IsIncapacitated() on Cybernetics_Civilian_V2_C" },
  { id = "health_props", kind = "game", method = "call_or_property", target = "Character", candidates = {"GetCurrentHealth", "Health", "CurrentHealth"}, used_by = "state_dead fallback, player_health", implemented = true, verified = false, source = "ReadyOrNotCharacter:GetCurrentHealth() (F9 recon; the player answers through it, AI share the class)" },
  { id = "player_health", kind = "game", method = "call_or_property", target = "player Pawn", candidates = {"GetCurrentHealth", "Health", "CurrentHealth"}, used_by = "hit_taken, power_absorb_hit", implemented = true, verified = true, source = "Health/CurrentHealth on BasePlayer_C are not numbers (RoN UE4SS.log); Get* calls tried next; F9 lists the pawn's health members; verified RoN UE4SS.log 2026-10-08: GetCurrentHealth() on BasePlayer_C (Health/CurrentHealth are objects, not numbers)" },
  { id = "player", kind = "engine", method = "find_all", target = "FindAllOf", candidates = {"PlayerController"}, used_by = "everything", implemented = true, verified = true, source = "first PlayerController whose Pawn IsPlayerControlled; UE4SS 3.0.1 UEHelpers.GetPlayerController calls an undefined Print and errors with no pawn (seen in RoN UE4SS.log); verified RoN UE4SS.log 2026-10-08 (Station hub): BP_BaseController_C (BP_MenuController_C has no pawn)" },
  { id = "camera", kind = "engine", method = "call", target = "PlayerCameraManager", candidates = {"GetCameraLocation", "GetCameraRotation"}, used_by = "aim attribution", implemented = true, verified = true, source = "game_info camera notes; verified RoN UE4SS.log 2026-10-08 (Station hub): answered" },
  { id = "fire_input", kind = "engine", method = "call", target = "PlayerController", candidates = {"IsInputKeyDown:LeftMouseButton", "IsInputKeyDown:Gamepad_RightTrigger"}, used_by = "kill / takedown attribution", implemented = true, verified = true, source = "APlayerController::IsInputKeyDown (engine); verified RoN UE4SS.log 2026-10-08: IsInputKeyDown LeftMouseButton" },
  { id = "aim_head", kind = "engine", method = "socket", target = "Character.Mesh", candidates = {"head", "Head", "neck_01"}, used_by = "headshot", implemented = true, verified = true, source = "UE mannequin bone names; check the log; verified RoN UE4SS.log 2026-10-08: socket 'head' on Cybernetics_Civilian_V2_C" },
  { id = "server_clock", kind = "engine", method = "call", target = "GameStateBase", candidates = {"GetServerWorldTimeSeconds"}, used_by = "all timing (shared clock, ready for co-op)", implemented = true, verified = true, source = "game_info players notes; verified RoN UE4SS.log 2026-10-08 (Station hub): answered" },
  { id = "map_name", kind = "engine", method = "call", target = "PlayerController", candidates = {"GetWorld():GetFName()"}, used_by = "mission start/end, level_clear reset", implemented = true, verified = true, source = "UE4SS native UObject:GetWorld/GetFName; GameplayStatics:GetCurrentLevelName crashed the game (UE4SS 3.0.1, RoN UE 5.3, breadcrumb in UE4SS.log); verified RoN UE4SS.log 2026-10-08 (Station hub): RoN_Station_Core" },
  { id = "move_speed", kind = "engine", method = "property", target = "Pawn.CharacterMovement", candidates = {"MaxWalkSpeed"}, used_by = "power_move_mult", implemented = true, verified = true, source = "UCharacterMovementComponent (engine); verified RoN UE4SS.log 2026-10-08 (Station hub): MaxWalkSpeed on BasePlayer_C" },
  { id = "anim_rate", kind = "engine", method = "property", target = "Pawn.Mesh", candidates = {"GlobalAnimRateScale"}, used_by = "power_anim_mult (reload speed)", implemented = true, verified = true, source = "USkeletalMeshComponent (engine); RoN may use separate first-person arms, check the log; verified RoN UE4SS.log 2026-10-08 (Station hub): GlobalAnimRateScale on BasePlayer_C" },
  { id = "hud_widget", kind = "engine", method = "call", target = "UMG", candidates = {"/Script/UMG.UserWidget", "/Script/UMG.WidgetTree", "/Script/UMG.CanvasPanel", "/Script/UMG.TextBlock", "/Script/UMG.Border"}, used_by = "the meter", implemented = true, verified = false, source = "StaticConstructObject of stock UMG classes, no editor; 2026-10-08 the first version (TextBlock + ProgressBar with default styles) was built and added to the viewport but nothing showed in game, so boxes are now plain Borders and the font is chosen explicitly (hud_font)" },
  { id = "hud_font", kind = "engine", method = "find_all", target = "UFont objects", candidates = {"/Engine/EngineFonts/Roboto.Roboto", "/Engine/EngineFonts/RobotoDistanceField.RobotoDistanceField", "Font"}, used_by = "every HUD text (a TextBlock with no cooked font draws nothing)", implemented = true, verified = false, source = "StaticFindObject on the engine fonts, else the first loaded UFont (FindAllOf Font); the mod logs the fonts it found" },
  { id = "world_change", kind = "ue4ss", method = "call", target = "PlayerController", candidates = {"GetWorld():GetAddress()"}, used_by = "pause reading the world for settings.load_resume_ms after a map load", implemented = true, verified = true, source = "UE4SS native; RegisterLoadMapPreHook/PostHook threw a C++ exception inside the engine at Ready or Not startup (UE4SS 3.0.1, crash report 2026-10-08), so loads are detected by the world changing; verified RoN UE4SS.log 2026-10-08: noticed the Station hub load" },
  { id = "key_mode", kind = "ue4ss", method = "keybind", target = "RegisterKeyBind", candidates = {"F7"}, used_by = "mode switch", implemented = true, verified = true, source = "settings.hotkey_mode; verified RoN UE4SS.log 2026-10-08: F7 cycled ultrakill/power/clean" },
  { id = "key_hud", kind = "ue4ss", method = "keybind", target = "RegisterKeyBind", candidates = {"F8"}, used_by = "show/hide meter", implemented = true, verified = false, source = "settings.hotkey_hud" },
  { id = "key_recon", kind = "ue4ss", method = "keybind", target = "RegisterKeyBind", candidates = {"F9"}, used_by = "dump classes and penalty functions to UE4SS.log", implemented = true, verified = true, source = "settings.hotkey_recon; verified RoN UE4SS.log 2026-10-08: F9 recon written" },
  { id = "penalty_suppress", kind = "game", method = "recon", target = "UFunction names", candidates = {"Penalt", "Unauthori", "ROE"}, used_by = "modes.suppress_ron_penalties", implemented = false, verified = false, source = "F9 recon 2026-10-08 lists ScoringManager:GivePenalty / GiveCustomPenalty / RevokeAllPenalties and ReadyOrNotCharacter:PlayROEViolateTOCResponse; hooking GivePenalty is the next-update candidate (not in v1)" },
}
S.hooks_by_id = {}
for _, r in ipairs(S.hooks) do S.hooks_by_id[r.id] = r end
S.hud = {
  { id = "panel", widget = "Border", shows = "panel", x = 460, y = 28, w = 440, h = 300, font_size = 0, color = "#000000B4" },
  { id = "mode", widget = "TextBlock", shows = "mode_label", x = 440, y = 36, w = 400, h = 22, font_size = 13, color = "#C8C8C8" },
  { id = "letter", widget = "TextBlock", shows = "rank_letter", x = 440, y = 54, w = 400, h = 104, font_size = 84, color = "rank" },
  { id = "suffix", widget = "TextBlock", shows = "rank_suffix", x = 440, y = 104, w = 400, h = 46, font_size = 32, color = "rank" },
  { id = "barback", widget = "Border", shows = "bar_back", x = 440, y = 162, w = 400, h = 12, font_size = 0, color = "#FFFFFF2E" },
  { id = "barfill", widget = "Border", shows = "bar_fill", x = 440, y = 162, w = 400, h = 12, font_size = 0, color = "rank" },
  { id = "feed", widget = "TextBlock", shows = "feed", x = 440, y = 184, w = 400, h = 136, font_size = 20, color = "#FFFFFF" },
  { id = "banner", widget = "TextBlock", shows = "banner", x = 460, y = 340, w = 440, h = 70, font_size = 22, color = "#FFD700" },
}
S.hud_by_id = {}
for _, r in ipairs(S.hud) do S.hud_by_id[r.id] = r end
S.modes = {
  { id = "clean", order = 0, label = "CLEAN", summary = "Arrests, takedowns and fast clears. Unauthorized force drops you to D.", suppress_ron_penalties = false, end_score = "ron", power_buffs = false, switch_sound = "sfx_mode_switch" },
  { id = "ultrakill", order = 1, label = "ULTRAKILL RULES", summary = "Kills, headshots and multi-kills feed the meter. Best rank is your score.", suppress_ron_penalties = true, end_score = "best_rank", power_buffs = false, switch_sound = "sfx_mode_switch" },
  { id = "power", order = 2, label = "POWER", summary = "Everything earns style. Rank makes you faster. ULTRAKILL rank shrugs off a hit.", suppress_ron_penalties = false, end_score = "best_rank", power_buffs = true, switch_sound = "sfx_mode_switch" },
}
S.modes_by_id = {}
for _, r in ipairs(S.modes) do S.modes_by_id[r.id] = r end
S.music_tiers = {
  { id = "calm", order = 0, clean_layer = "music_clean", battle_layer = "music_battle", clean_gain = 0.35, battle_gain = 0.0, crossfade_s = 3.0 },
  { id = "drive", order = 1, clean_layer = "music_clean", battle_layer = "music_battle", clean_gain = 0.75, battle_gain = 0.0, crossfade_s = 2.0 },
  { id = "combat", order = 2, clean_layer = "music_clean", battle_layer = "music_battle", clean_gain = 0.0, battle_gain = 0.8, crossfade_s = 1.0 },
  { id = "ultra", order = 3, clean_layer = "music_clean", battle_layer = "music_battle", clean_gain = 0.0, battle_gain = 1.0, crossfade_s = 0.5 },
}
S.music_tiers_by_id = {}
for _, r in ipairs(S.music_tiers) do S.music_tiers_by_id[r.id] = r end
S.ranks = {
  { id = "d", order = 0, letter = "D", name = "DESTRUCTIVE", threshold = 0, decay_per_s = 6, color = "#4A90E2", up_sound = "sfx_rank_up", music_tier = "calm", power_move_mult = 1.0, power_anim_mult = 1.0, power_absorb_hit = false },
  { id = "c", order = 1, letter = "C", name = "CHAOTIC", threshold = 100, decay_per_s = 10, color = "#4CD964", up_sound = "sfx_rank_up", music_tier = "calm", power_move_mult = 1.03, power_anim_mult = 1.03, power_absorb_hit = false },
  { id = "b", order = 2, letter = "B", name = "BRUTAL", threshold = 250, decay_per_s = 15, color = "#FFCC00", up_sound = "sfx_rank_up", music_tier = "drive", power_move_mult = 1.06, power_anim_mult = 1.06, power_absorb_hit = false },
  { id = "a", order = 3, letter = "A", name = "ANARCHIC", threshold = 450, decay_per_s = 20, color = "#FF9500", up_sound = "sfx_rank_up", music_tier = "drive", power_move_mult = 1.1, power_anim_mult = 1.1, power_absorb_hit = false },
  { id = "s", order = 4, letter = "S", name = "SUPREME", threshold = 700, decay_per_s = 27, color = "#FF3B30", up_sound = "sfx_rank_up_high", music_tier = "combat", power_move_mult = 1.14, power_anim_mult = 1.15, power_absorb_hit = false },
  { id = "ss", order = 5, letter = "SS", name = "SSADISTIC", threshold = 1000, decay_per_s = 36, color = "#FF2D55", up_sound = "sfx_rank_up_high", music_tier = "combat", power_move_mult = 1.18, power_anim_mult = 1.2, power_absorb_hit = false },
  { id = "sss", order = 6, letter = "SSS", name = "SSSHITSTORM", threshold = 1400, decay_per_s = 50, color = "#D40000", up_sound = "sfx_rank_up_high", music_tier = "ultra", power_move_mult = 1.22, power_anim_mult = 1.25, power_absorb_hit = false },
  { id = "ultrakill", order = 7, letter = "ULTRAKILL", name = "ULTRAKILL", threshold = 1900, decay_per_s = 70, color = "#FFD700", up_sound = "sfx_rank_ultrakill", music_tier = "ultra", power_move_mult = 1.28, power_anim_mult = 1.3, power_absorb_hit = true },
}
S.ranks_by_id = {}
for _, r in ipairs(S.ranks) do S.ranks_by_id[r.id] = r end
S.settings = {
  { id = "hotkey_mode", value = "F7", desc = "Cycle Clean → ULTRAKILL Rules → Power" },
  { id = "hotkey_hud", value = "F8", desc = "Show or hide the meter" },
  { id = "hotkey_recon", value = "F9", desc = "(F10-F12 and ~ are UE4SS ConsoleEnabler console keys) Write classes, hook results and penalty functions to UE4SS.log" },
  { id = "trace_steps", value = true, desc = "Log each engine step once before it first runs, so a crash names its call in UE4SS.log" },
  { id = "recon_member_words", value = "Health|Dead|Death|Arrest|Restrain|Surrender|Incap|Stun|Damage|Equipped|Weapon|Firearm|Item|Inventory|Fire", desc = "Recon lists the player pawn's properties and functions containing these ('|'-separated)" },
  { id = "load_resume_ms", value = 2000, desc = "After the player turns up in a new world (a map load), wait this long before reading it" },
  { id = "hud_glyph_w", value = 0.66, desc = "Width of one rank-letter glyph as a fraction of its font size (places the rank suffix after the letter, shrinks long letters such as ULTRAKILL)" },
  { id = "hud_typeface", value = "Bold", desc = "Typeface of the HUD font (Slate falls back to the font's default if it has none by that name)" },
  { id = "hud_shear", value = -14, desc = "Render-transform shear (degrees) on the rank text and feed, for ULTRAKILL's italic look with any font" },
  { id = "poll_ms", value = 100, desc = "How often the mod reads the game" },
  { id = "fire_window_s", value = 0.8, desc = "A death this soon after the player fired counts as theirs" },
  { id = "aim_cone_deg", value = 10, desc = "Victim must be this close to the crosshair to be the player's kill" },
  { id = "headshot_cone_deg", value = 2.5, desc = "Head this close to the crosshair = headshot" },
  { id = "player_reach_cm", value = 350, desc = "Arrests/takedowns closer than this are the player's" },
  { id = "multikill_window_s", value = 1.5, desc = "Kills this close together are a multikill" },
  { id = "chain_window_s", value = 4.0, desc = "Neutralizations this close together are a fast clear" },
  { id = "style_cap", value = 2400, desc = "Meter maximum" },
  { id = "feed_lines", value = 5, desc = "Lines kept in the HUD feed" },
  { id = "data_dir", value = "{localappdata}/RoNUltrakill", desc = "Folder for settings.cfg, events.log, clip-index.txt, logs" },
  { id = "settings_file", value = "{localappdata}/RoNUltrakill/settings.cfg", desc = "Melty writes ULTRAKILL_DIR here before every Play" },
  { id = "settings_file_mod", value = "{mod}/settings.cfg", desc = "Read when settings_file has no ULTRAKILL_DIR (manual installs; a launcher whose %LOCALAPPDATA% writes are virtualized)" },
  { id = "events_file", value = "{localappdata}/RoNUltrakill/events.log", desc = "Lua appends, helper tails" },
  { id = "heartbeat_file", value = "{localappdata}/RoNUltrakill/helper.alive", desc = "Helper touches it every second" },
  { id = "music_pair_strip", value = "(?i)\\b(clean|battle)\\b", desc = "Removed from music clip names to pair a clean track with its battle version ('0-2 Clean' <-> '0-2')" },
  { id = "game_process", value = "ReadyOrNotSteam-Win64-Shipping|ReadyOrNot-Win64-Shipping", desc = "Helper exits when none of these processes ('|'-separated) is running; the Steam build's exe is ReadyOrNotSteam-Win64-Shipping.exe" },
}
S.settings_by_id = {}
for _, r in ipairs(S.settings) do S.settings_by_id[r.id] = r end
S.style_events = {
  { id = "arrest", feed_text = "+ ARRESTED", detect = "state_arrested", rule = "a suspect or civilian becomes arrested within settings.player_reach_cm of the player", points_clean = 150, points_ultrakill = 20, points_power = 120, effect_clean = "none", effect_ultrakill = "none", effect_power = "none" },
  { id = "squad_arrest", feed_text = "+ SQUAD CUFFS", detect = "state_arrested", rule = "an arrest happens farther than settings.player_reach_cm from the player (the AI squad did it)", points_clean = 40, points_ultrakill = 0, points_power = 30, effect_clean = "none", effect_ultrakill = "none", effect_power = "none" },
  { id = "compliance", feed_text = "+ COMPLIANCE", detect = "state_surrendered", rule = "a suspect surrenders while the player can see them (inside settings.aim_cone_deg x3)", points_clean = 40, points_ultrakill = 0, points_power = 30, effect_clean = "none", effect_ultrakill = "none", effect_power = "none" },
  { id = "takedown", feed_text = "+ SUBDUED", detect = "state_incapacitated", rule = "a suspect becomes incapacitated but not dead, after the player fired at them or within reach", points_clean = 110, points_ultrakill = 30, points_power = 90, effect_clean = "none", effect_ultrakill = "none", effect_power = "none" },
  { id = "kill", feed_text = "+ KILL", detect = "state_dead", rule = "a suspect who was not surrendered or arrested dies within settings.fire_window_s of the player firing at them", points_clean = 15, points_ultrakill = 70, points_power = 60, effect_clean = "none", effect_ultrakill = "none", effect_power = "none" },
  { id = "headshot", feed_text = "+ HEADSHOT", detect = "aim_head", rule = "on a kill, the camera was within settings.headshot_cone_deg of the victim's head", points_clean = 0, points_ultrakill = 50, points_power = 40, effect_clean = "none", effect_ultrakill = "none", effect_power = "none" },
  { id = "multikill", feed_text = "+ MULTIKILL", detect = "state_dead", rule = "a second (or later) kill within settings.multikill_window_s of the last one", points_clean = 0, points_ultrakill = 120, points_power = 100, effect_clean = "none", effect_ultrakill = "none", effect_power = "none" },
  { id = "unauthorized_kill", feed_text = "+ UNAUTHORIZED", detect = "state_dead", rule = "a civilian, or a suspect who had surrendered or was arrested, dies after the player fired at them", points_clean = 0, points_ultrakill = 70, points_power = 0, effect_clean = "drop_to_d", effect_ultrakill = "none", effect_power = "drop_one_rank" },
  { id = "fast_clear", feed_text = "+ FAST CLEAR", detect = "state_arrested", rule = "a player arrest or takedown within settings.chain_window_s of the previous one", points_clean = 90, points_ultrakill = 0, points_power = 60, effect_clean = "none", effect_ultrakill = "none", effect_power = "none" },
  { id = "level_clear", feed_text = "+ AREA SECURED", detect = "characters", rule = "every suspect seen on this map is dead, arrested or incapacitated, and at least one was neutralized while the mod watched (fires once per map)", points_clean = 400, points_ultrakill = 250, points_power = 300, effect_clean = "none", effect_ultrakill = "none", effect_power = "none" },
  { id = "hit_taken", feed_text = "- HURT", detect = "player_health", rule = "the player's health goes down", points_clean = -60, points_ultrakill = 0, points_power = 0, effect_clean = "none", effect_ultrakill = "drop_one_rank", effect_power = "drop_one_rank" },
}
S.style_events_by_id = {}
for _, r in ipairs(S.style_events) do S.style_events_by_id[r.id] = r end
return S
